##################################################################################################
# Config service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-config-service
  namespace: flomesh-spring
  labels:
    app: config
    service: samples-config-service
spec:
  ports:
    - port: 8888
      name: http
      targetPort: 8888
  selector:
    app: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-config-service-v1
  namespace: flomesh-spring
  labels:
    app: config
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
      version: v1
  template:
    metadata:
      labels:
        app: config
        version: v1
        service: samples-config-service
    spec:
      initContainers:
        - name: check-discovery
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |-
              until nc -vz samples-discovery-server 8761; \
                do echo "Waiting for Eureka ready ..."; \
                sleep 5; \
              done;
      containers:
        - name: app
          image: docker.io/flomesh/samples-config-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
              value: samples-discovery-server
            - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
              value: "8771"
            - name: K8S_SAMPLES_BOOKINFO_RATINGS_HOSTNAME
              value: samples-bookinfo-ratings
            - name: K8S_SERVICE_NAME
              value: samples-config-service
          resources:
            limits:
              memory: 300Mi
            requests:
              memory: 300Mi