##################################################################################################
# Discovery service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-discovery-server
  namespace: flomesh-spring
  labels:
    app: discovery
    service: samples-discovery-server
spec:
  ports:
    - port: 8761
      name: http
      targetPort: 8761
    - port: 8771
      name: sidecar
      targetPort: 8771
  selector:
    app: discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-discovery-server-v1
  namespace: flomesh-spring
  labels:
    app: discovery
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
      version: v1
  template:
    metadata:
      labels:
        app: discovery
        version: v1
        service: samples-discovery-server
        sys: bookinfo-samples
      annotations:
        "flomesh.io/inject": "true"
        "service.flomesh.io/name": "samples-discovery-server"
        "service.flomesh.io/port": "8761"
    spec:
      containers:
        - name: app
          image: docker.io/flomesh/samples-discovery-server:loong64
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
              value: samples-discovery-server
            - name: K8S_SERVICE_NAME
              value: samples-discovery-server
            - name: _samples_pod_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: _samples_pod_nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: _samples_pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: _samples_pod_serviceName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
            - name: _samples_pod_serviceVersion
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: _samples_pod_serviceFullName
              value: $(_samples_pod_serviceName)-$(_samples_pod_serviceVersion)
            - name: _samples_pod_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: _samples_pod_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: _samples_pod_hostIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 300Mi
