apiVersion: v1
kind: Endpoints
metadata:
  name: samples-metrics
  namespace: flomesh-spring
  labels:
    app: metrics
    service: metrics
subsets:
  - addresses:
      - ip: 10.0.0.60
    ports:
      - name: pg
        port: 9001
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: samples-metrics
  namespace: flomesh-spring
  labels:
    app: metrics
    service: metrics
spec:
  ports:
    - port: 9001
      name: pg
      targetPort: 9001
---