##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-bookinfo-productpage-v2
  namespace: flomesh-spring
  labels:
    app: productpage
    service: samples-bookinfo-productpage-v2
spec:
  ports:
    - port: 9080
      name: http
      targetPort: 9080
    - port: 9090
      name: sidecar
      targetPort: 9090
  selector:
    app: productpage
    version: v2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-bookinfo-productpage-v2
  namespace: flomesh-spring
  labels:
    app: productpage
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      labels:
        app: productpage
        version: v2
        service: samples-bookinfo-productpage
        sys: bookinfo-samples
      annotations:
        "flomesh.io/inject": "true"
        service.flomesh.io/name: "samples-bookinfo-productpage-v2"
    spec:
      initContainers:
        - name: check-config
          image: docker.io/flomesh/busybox:loong64
          command: [ "/bin/sh", "-c" ]
          args:
            - |-
              until nc -vz samples-api-gateway-v2 10010; \
                do echo "Waiting for API Gateway ready ..."; \
                sleep 5; \
              done;
      containers:
        - name: app
          env:
            - name: SERVICES_DOMAIN
              value: flomesh-spring.svc
            - name: K8S_SAMPLES_API_GATEWAY_HOSTNAME
              value: samples-api-gateway-v2
            - name: K8S_SAMPLES_API_GATEWAY_PORT
              value: "10010"
            - name: _samples_pod_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: _samples_pod_nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: _samples_pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: _samples_pod_serviceName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
            - name: _samples_pod_serviceVersion
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: _samples_pod_serviceFullName
              value: $(_samples_pod_serviceName)-$(_samples_pod_serviceVersion)
            - name: _samples_pod_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: _samples_pod_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: _samples_pod_hostIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: flomesh/samples-bookinfo-productpage:loong64
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          resources:
            limits:
              memory: 300Mi
              cpu: 100m
---
